container:
  image: rust:latest

test_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

test_continuous_download_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat continuous_download/Cargo.toml
  build_script: cd continuous_download && cargo build
  test_script: cd continuous_download && cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

test_sorted_stream_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat sorted_stream/Cargo.toml
  build_script: cd sorted_stream && cargo build
  test_script: cd sorted_stream && cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
