container:
  image: rust:latest

test_task:
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock continuous_download/Cargo.toml sorted_stream/Cargo.toml
  build_script: cargo build --workspace
  test_script: cargo test --workspace
  before_cache_script: rm -rf $CARGO_HOME/registry/index
