[package]
name = "wikidata-realtime-dumps"
version = "0.1.0"
authors = ["Aleksey Bekh-Ivanov <6ex@mail.ru>"]
edition = "2018"

[profile.dev]
panic = 'abort'
[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix="0.9.0"
actix-web={version="2.0.0", features=["rustls"]}
actix-rt = "1.0.0"
futures = "0.3.1"
bytes = "0.5.3"
sse-codec = {version="0.1.0", git="https://github.com/bekh6ex/sse-codec.git", branch="fix-stream-bug"}
serde = "1.0.104"
serde_json = "1.0.44"
log = "0.4.8"
async-std = "1.4.0"
flate2 = "1.0.13"
pin-utils = "0.1.0-alpha.4"
futures-util = "0.3.1"
# TODO try out either of the following
#futures-retry = "0.4.0"
#backoff = "0.1.5"
measure_time = "0.6"
hyper = "0.13"
hyper-rustls = "0.19.0"
log4rs = "0.9.0"
